format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device_cdc}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device_cdc}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_BULK_IN_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_cdc_0, value: '2'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_BULK_OUT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_cdc_0, value: '2'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INTERFACE_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_cdc_0, value: '0'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_cdc_0, value: '1'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: USB Device}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sys_console_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: sys_console_USB_DEVICE_CDC_dependency}
- type: ElementPosition
  attributes: {x: '5', y: '167', id: usb_device_cdc}
