#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# pic32mz_w1_eth_wifi_freertos configuration
CND_ARTIFACT_DIR_pic32mz_w1_eth_wifi_freertos=dist/pic32mz_w1_eth_wifi_freertos/production
CND_ARTIFACT_NAME_pic32mz_w1_eth_wifi_freertos=pic32mz_w1_curiosity_freertos.X.production.hex
CND_ARTIFACT_PATH_pic32mz_w1_eth_wifi_freertos=dist/pic32mz_w1_eth_wifi_freertos/production/pic32mz_w1_curiosity_freertos.X.production.hex
