format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDhcps}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_IP_ADDRESS_RANGE_START_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.200}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_GATEWAY_ADDRESS_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_IP_ADDRESS_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_NETMASK_ADDRESS_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.0}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_PRIMARY_DNS_ADDRESS_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.1}
  - type: String
    attributes: {id: TCPIP_DHCPS_DEFAULT_SERVER_SECONDARY_DNS_ADDRESS_IDX1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.1}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcps, value: '524'}
  - type: Boolean
    attributes: {id: TCPIP_DHCP_SERVER_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcps, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_INSTANCES_NUMBER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '300', y: '26', id: tcpipDhcps}
