format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_AP_SSIDVISIBILE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_WIFI_AP_SSID_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DEMO_AP_SOFTAP}
  - type: Combo
    attributes: {id: SYS_WIFI_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: STA}
  - type: Boolean
    attributes: {id: SYS_WIFI_STA_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_WIFI_STA_SSID_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DEMO_AP_SOFTAP}
- type: ElementPosition
  attributes: {x: '28', y: '61', id: sysWifiPic32mzw1}
