format_version: v1.0
type: UniqueComponent
attributes: {id: sys_command}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_COMMAND_MAX_CMD_ARGS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiProvPic32mzw1, value: '10'}
  - type: Integer
    attributes: {id: SYS_COMMAND_PRINT_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8192'}
  - type: Integer
    attributes: {id: SYS_COMMAND_RTOS_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '4096'}
  - type: String
    attributes: {id: SYS_CONSOLE_DEVICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_command, value: SYS_CONSOLE_0}
  - type: String
    attributes: {id: SYS_CONSOLE_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_command, value: '0'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: sys_command_SYS_CONSOLE_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console}
- type: ElementPosition
  attributes: {x: '386', y: '133', id: sys_command}
