format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipStack}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_STACK_CALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: calloc}
      - type: User
        attributes: {value: APP_Calloc}
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_RUN_LIMIT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_STACK_DRAM_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '65000'}
  - type: String
    attributes: {id: TCPIP_STACK_FREE_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: free}
      - type: User
        attributes: {value: vPortFree}
  - type: Integer
    attributes: {id: TCPIP_STACK_HEAP_SIZE_RECOMMEND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '35'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INTERFACE_CHANGE_SIGNALING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INTERRUPT_EN_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_INT_MAC_IDX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_STACK_MAC_CLOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '0'}
  - type: String
    attributes: {id: TCPIP_STACK_MALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: malloc}
      - type: User
        attributes: {value: pvPortMalloc}
  - type: String
    attributes: {id: TCPIP_STACK_MII_MODE_IDX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: ''}
  - type: Menu
    attributes: {id: TCPIP_STACK_NET_INTERFACE_MENU_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_STACK_NET_INTERFACE_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: PIC32MZW1}
  - type: String
    attributes: {id: TCPIP_STACK_NET_INTERFACE_NAME_IDX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: ''}
  - type: Integer
    attributes: {id: TCPIP_STACK_NET_INTERFACE_NUM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: '1'}
  - type: String
    attributes: {id: TCPIP_STACK_OTH_INT_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_SYS_RANDOM_H2_ADAPTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipStack, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_USER_NOTIFICATION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: 'true'}
  - type: Combo
    attributes: {id: TCPIP_STACK_USE_HEAP_CONFIG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: TCPIP_STACK_HEAP_TYPE_EXTERNAL_HEAP}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Core_SysConsole_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console}
- type: ElementPosition
  attributes: {x: '388', y: '294', id: tcpipStack}
