configName: pic32mz_w1_eth_wifi_freertos
folderName: pic32mz_w1_curiosity_freertos
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ1025W104132
projectName: pic32mz_w1_curiosity_freertos
settings:
  PackageFilter: bsp;core;crypto;cryptoauthlib;csp;dev_packs;net;quick_docs;touch;touch_apps;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.5.203\atdf\PIC32MZ1025W104132.atdf
