format_version: v1.0
type: GeneratorComponent
attributes: {id: sys_console}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_CONSOLE_PRINT_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '256'}
      - type: User
        attributes: {value: '8192'}
  - type: Integer
    attributes: {id: SYS_CONSOLE_UART_CONNECTION_COUNTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_console, value: '1'}
  - type: Integer
    attributes: {id: SYS_CONSOLE_USB_CONNECTION_COUNTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_console, value: '7'}
  - type: Integer
    attributes: {id: SYS_CONSOLE_USB_READ_WRITE_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_console, value: '64'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: sys_console}
    children:
    - type: Symbols
      children:
      - type: Comment
        attributes: {id: SYS_CONSOLE_BUFFER_CONFIG_COMMENT}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: UART1}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: '0'}
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE_SET}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: UART}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_UART_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console, value: '0'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_USB_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console, value: '0'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RTOS_STACK_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '1024'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RX_BUFFER_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '128'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_TX_BUFFER_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '1024'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: SYS_CONSOLE_USB_DEVICE_SPEED}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: Full Speed}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: sys_console_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: uart1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: UART1_UART}
  - type: InstanceComponent
    attributes: {instance: '1', id: sys_console}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: USB_DEVICE_CDC_0}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: '0'}
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE_SET}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: USB_CDC}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_USB_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console, value: '0'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RTOS_DELAY}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '1'}
      - type: Menu
        attributes: {id: SYS_CONSOLE_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: '4096'}
      - type: File
        attributes: {id: SYS_CONSOLE_SYS_RTOS_TASK}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_TX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: '4096'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_CDC_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: SYS_CONSOLE_USB_DEVICE_SPEED}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: Full Speed}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '197', y: '139', id: sys_console}
