format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipArp}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_ARP_CACHE_ENTRIES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '15'}
  - type: Integer
    attributes: {id: TCPIP_ARP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipArp, value: '462'}
- type: ElementPosition
  attributes: {x: '420', y: '20', id: tcpipArp}
